---
title: "Programming"
author: "Sebastian Krantz"
date: "5 6 2020"
output: html_document
---

# Programming

```{r}
g <- GRP(wlddev, c("country", "decade"), return.order = TRUE)
g

head(add_vars(g[["groups"]], fmean(get_vars(wlddev, 9:12), g, use.g.names = FALSE)))
```

## Creating own grouped functions in C++

Here I show how one can use these tools 

```{r}
str(g)
```

```{Rcpp, eval = FALSE}
// [[Rcpp::plugins(cpp11)]]
#include <Rcpp.h>
using namespace Rcpp;

template <int RTYPE>
LogicalVector ganyNACppImpl(Vector<RTYPE> x, int ng, IntegerVector g) {
  int l = x.size();
  if(l != g.size()) stop("length(x) must match length(g)");
  LogicalVector out(ng);

  if(RTYPE == REALSXP) { // numeric vector: all logical operations on NA/NaN evaluate to false, except != which is true.
    for(int i = 0; i != l; ++i) if(x[i] != x[i]) out[g[i]-1] = true;
  } else { // other vectors
    for(int i = 0; i != l; ++i) if(x[i] == Vector<RTYPE>::get_na()) out[g[i]-1] = true;
  }

  return out;
}

// disabling other types
template <>
LogicalVector ganyNACppImpl(Vector<CPLXSXP> x, int ng, IntegerVector) {
  stop("Not supported SEXP type!");
}

template <>
LogicalVector ganyNACppImpl(Vector<VECSXP> x, int ng, IntegerVector) {
  stop("Not supported SEXP type!");
}

template <>
LogicalVector ganyNACppImpl(Vector<RAWSXP> x, int ng, IntegerVector) {
  stop("Not supported SEXP type!");
}

template <>
LogicalVector ganyNACppImpl(Vector<EXPRSXP> x, int ng, IntegerVector) {
  stop("Not supported SEXP type!");
}

// [[Rcpp::export]]
LogicalVector ganyNACpp(const SEXP& x, int ng = 0, const IntegerVector& g = 0){
  RCPP_RETURN_VECTOR(ganyNACppImpl, x, ng, g);
}

```
On the R side things are then pretty simple: 
```{r, message=FALSE}
library(Rcpp)
sourceCpp("ganyNA.cpp")

ganyNA <- function(x, g, use.g.names = TRUE) {
  if(is.atomic(g) || !is_GRP(g)) g <- GRP(g, return.groups = use.g.names)
  if(use.g.names) setNames(ganyNACpp(x, g[[1L]], g[[2L]]), GRPnames(g, FALSE)) else
    ganyNACpp(x, g[[1L]], g[[2L]])
}

ganyNA(wlddev$PCGDP, wlddev$year)

# 10 million obs and 1 million groups, 1% of data missing
x <- na_insert(rnorm(1e7), prop = 0.01)
g <- sample.int(1e6, 1e7, TRUE)
system.time(ganyNA(x, g))
system.time(ganyNA(x, g, use.g.names = FALSE))

```

We could additionally add a `TRA` argument and then internally call the `TRA()` function to allow for replacing and sweeping out statistics, but this does not make much sense here. 

