# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BWCpp <- function(x, ng = 0L, g = 0L, gs = NULL, w = NULL, narm = TRUE, option = FALSE, B = FALSE) {
    .Call(Cpp_BW, x, ng, g, gs, w, narm, option, B)
}

BWmCpp <- function(x, ng = 0L, g = 0L, gs = NULL, w = NULL, narm = TRUE, option = FALSE, B = FALSE) {
    .Call(Cpp_BWm, x, ng, g, gs, w, narm, option, B)
}

BWlCpp <- function(x, ng = 0L, g = 0L, gs = NULL, w = NULL, narm = TRUE, option = FALSE, B = FALSE) {
    .Call(Cpp_BWl, x, ng, g, gs, w, narm, option, B)
}

TRACpp <- function(x, xAG, g = 0L, ret = 1L) {
    .Call(Cpp_TRA, x, xAG, g, ret)
}

TRAmCpp <- function(x, xAG, g = 0L, ret = 1L) {
    .Call(Cpp_TRAm, x, xAG, g, ret)
}

TRAlCpp <- function(x, xAG, g = 0L, ret = 1L) {
    .Call(Cpp_TRAl, x, xAG, g, ret)
}

fNdistinctCpp <- function(x, ng = 0L, g = 0L, gs = NULL, narm = TRUE) {
    .Call(Cpp_fNdistinct, x, ng, g, gs, narm)
}

fNdistinctlCpp <- function(x, ng = 0L, g = 0L, gs = NULL, narm = TRUE, drop = TRUE) {
    .Call(Cpp_fNdistinctl, x, ng, g, gs, narm, drop)
}

fNdistinctmCpp <- function(x, ng = 0L, g = 0L, gs = NULL, narm = TRUE, drop = TRUE) {
    .Call(Cpp_fNdistinctm, x, ng, g, gs, narm, drop)
}

fNobsCpp <- function(x, ng = 0L, g = 0L) {
    .Call(Cpp_fNobs, x, ng, g)
}

fNobsmCpp <- function(x, ng = 0L, g = 0L, drop = TRUE) {
    .Call(Cpp_fNobsm, x, ng, g, drop)
}

fNobslCpp <- function(x, ng = 0L, g = 0L, drop = TRUE) {
    .Call(Cpp_fNobsl, x, ng, g, drop)
}

fbstatsCpp <- function(x, ext = FALSE, ng = 0L, g = 0L, npg = 0L, pg = 0L, w = NULL, array = TRUE, setn = TRUE, gn = NULL) {
    .Call(Cpp_fbstats, x, ext, ng, g, npg, pg, w, array, setn, gn)
}

fbstatsmCpp <- function(x, ext = FALSE, ng = 0L, g = 0L, npg = 0L, pg = 0L, w = NULL, array = TRUE, gn = NULL) {
    .Call(Cpp_fbstatsm, x, ext, ng, g, npg, pg, w, array, gn)
}

fbstatslCpp <- function(x, ext = FALSE, ng = 0L, g = 0L, npg = 0L, pg = 0L, w = NULL, array = TRUE, gn = NULL) {
    .Call(Cpp_fbstatsl, x, ext, ng, g, npg, pg, w, array, gn)
}

fdiffCpp <- function(x, n = 1L, diff = 1L, fill = NA_real_, ng = 0L, g = 0L, gs = NULL, t = NULL, names = TRUE) {
    .Call(Cpp_fdiff, x, n, diff, fill, ng, g, gs, t, names)
}

fdiffmCpp <- function(x, n = 1L, diff = 1L, fill = NA_real_, ng = 0L, g = 0L, gs = NULL, t = NULL, names = TRUE) {
    .Call(Cpp_fdiffm, x, n, diff, fill, ng, g, gs, t, names)
}

fdifflCpp <- function(x, n = 1L, diff = 1L, fill = NA_real_, ng = 0L, g = 0L, gs = NULL, t = NULL, names = TRUE) {
    .Call(Cpp_fdiffl, x, n, diff, fill, ng, g, gs, t, names)
}

ffirstCpp <- function(x, ng = 0L, g = 0L, narm = TRUE) {
    .Call(Cpp_ffirst, x, ng, g, narm)
}

ffirstmCpp <- function(x, ng = 0L, g = 0L, narm = TRUE, drop = TRUE) {
    .Call(Cpp_ffirstm, x, ng, g, narm, drop)
}

ffirstlCpp <- function(x, ng = 0L, g = 0L, narm = TRUE) {
    .Call(Cpp_ffirstl, x, ng, g, narm)
}

fgrowthCpp <- function(x, n = 1L, diff = 1L, fill = NA_real_, ng = 0L, g = 0L, gs = NULL, t = NULL, logdiff = FALSE, names = TRUE) {
    .Call(Cpp_fgrowth, x, n, diff, fill, ng, g, gs, t, logdiff, names)
}

fgrowthmCpp <- function(x, n = 1L, diff = 1L, fill = NA_real_, ng = 0L, g = 0L, gs = NULL, t = NULL, logdiff = FALSE, names = TRUE) {
    .Call(Cpp_fgrowthm, x, n, diff, fill, ng, g, gs, t, logdiff, names)
}

fgrowthlCpp <- function(x, n = 1L, diff = 1L, fill = NA_real_, ng = 0L, g = 0L, gs = NULL, t = NULL, logdiff = FALSE, names = TRUE) {
    .Call(Cpp_fgrowthl, x, n, diff, fill, ng, g, gs, t, logdiff, names)
}

flagleadCpp <- function(x, n = 1L, fill = NULL, ng = 0L, g = 0L, gs = NULL, t = NULL, names = TRUE) {
    .Call(Cpp_flaglead, x, n, fill, ng, g, gs, t, names)
}

flagleadmCpp <- function(x, n = 1L, fill = NULL, ng = 0L, g = 0L, gs = NULL, t = NULL, names = TRUE) {
    .Call(Cpp_flagleadm, x, n, fill, ng, g, gs, t, names)
}

flagleadlCpp <- function(x, n = 1L, fill = NULL, ng = 0L, g = 0L, gs = NULL, t = NULL, names = TRUE) {
    .Call(Cpp_flagleadl, x, n, fill, ng, g, gs, t, names)
}

flastCpp <- function(x, ng = 0L, g = 0L, narm = TRUE) {
    .Call(Cpp_flast, x, ng, g, narm)
}

flastmCpp <- function(x, ng = 0L, g = 0L, narm = TRUE, drop = TRUE) {
    .Call(Cpp_flastm, x, ng, g, narm, drop)
}

flastlCpp <- function(x, ng = 0L, g = 0L, narm = TRUE) {
    .Call(Cpp_flastl, x, ng, g, narm)
}

fmaxCpp <- function(x, ng = 0L, g = 0L, narm = TRUE) {
    .Call(Cpp_fmax, x, ng, g, narm)
}

fmaxmCpp <- function(x, ng = 0L, g = 0L, narm = TRUE, drop = TRUE) {
    .Call(Cpp_fmaxm, x, ng, g, narm, drop)
}

fmaxlCpp <- function(x, ng = 0L, g = 0L, narm = TRUE, drop = TRUE) {
    .Call(Cpp_fmaxl, x, ng, g, narm, drop)
}

fmeanCpp <- function(x, ng = 0L, g = 0L, gs = NULL, w = NULL, narm = TRUE) {
    .Call(Cpp_fmean, x, ng, g, gs, w, narm)
}

fmeanmCpp <- function(x, ng = 0L, g = 0L, gs = NULL, w = NULL, narm = TRUE, drop = TRUE) {
    .Call(Cpp_fmeanm, x, ng, g, gs, w, narm, drop)
}

fmeanlCpp <- function(x, ng = 0L, g = 0L, gs = NULL, w = NULL, narm = TRUE, drop = TRUE) {
    .Call(Cpp_fmeanl, x, ng, g, gs, w, narm, drop)
}

fmedianCpp <- function(x, ng = 0L, g = 0L, gs = NULL, narm = TRUE) {
    .Call(Cpp_fmedian, x, ng, g, gs, narm)
}

fmedianmCpp <- function(x, ng = 0L, g = 0L, gs = NULL, narm = TRUE, drop = TRUE) {
    .Call(Cpp_fmedianm, x, ng, g, gs, narm, drop)
}

fmedianlCpp <- function(x, ng = 0L, g = 0L, gs = NULL, narm = TRUE, drop = TRUE) {
    .Call(Cpp_fmedianl, x, ng, g, gs, narm, drop)
}

fminCpp <- function(x, ng = 0L, g = 0L, narm = TRUE) {
    .Call(Cpp_fmin, x, ng, g, narm)
}

fminmCpp <- function(x, ng = 0L, g = 0L, narm = TRUE, drop = TRUE) {
    .Call(Cpp_fminm, x, ng, g, narm, drop)
}

fminlCpp <- function(x, ng = 0L, g = 0L, narm = TRUE, drop = TRUE) {
    .Call(Cpp_fminl, x, ng, g, narm, drop)
}

fmodeCpp <- function(x, ng = 0L, g = 0L, gs = NULL, w = NULL, narm = TRUE) {
    .Call(Cpp_fmode, x, ng, g, gs, w, narm)
}

fmodelCpp <- function(x, ng = 0L, g = 0L, gs = NULL, w = NULL, narm = TRUE) {
    .Call(Cpp_fmodel, x, ng, g, gs, w, narm)
}

fmodemCpp <- function(x, ng = 0L, g = 0L, gs = NULL, w = NULL, narm = TRUE, drop = TRUE) {
    .Call(Cpp_fmodem, x, ng, g, gs, w, narm, drop)
}

fprodCpp <- function(x, ng = 0L, g = 0L, narm = TRUE) {
    .Call(Cpp_fprod, x, ng, g, narm)
}

fprodmCpp <- function(x, ng = 0L, g = 0L, narm = TRUE, drop = TRUE) {
    .Call(Cpp_fprodm, x, ng, g, narm, drop)
}

fprodlCpp <- function(x, ng = 0L, g = 0L, narm = TRUE, drop = TRUE) {
    .Call(Cpp_fprodl, x, ng, g, narm, drop)
}

fscaleCpp <- function(x, ng = 0L, g = 0L, gs = NULL, w = NULL, narm = TRUE, stable_algo = TRUE) {
    .Call(Cpp_fscale, x, ng, g, gs, w, narm, stable_algo)
}

fscalemCpp <- function(x, ng = 0L, g = 0L, gs = NULL, w = NULL, narm = TRUE, stable_algo = TRUE) {
    .Call(Cpp_fscalem, x, ng, g, gs, w, narm, stable_algo)
}

fscalelCpp <- function(x, ng = 0L, g = 0L, gs = NULL, w = NULL, narm = TRUE, stable_algo = TRUE) {
    .Call(Cpp_fscalel, x, ng, g, gs, w, narm, stable_algo)
}

fsumCpp <- function(x, ng = 0L, g = 0L, narm = TRUE) {
    .Call(Cpp_fsum, x, ng, g, narm)
}

fsummCpp <- function(x, ng = 0L, g = 0L, narm = TRUE, drop = TRUE) {
    .Call(Cpp_fsumm, x, ng, g, narm, drop)
}

fsumlCpp <- function(x, ng = 0L, g = 0L, narm = TRUE, drop = TRUE) {
    .Call(Cpp_fsuml, x, ng, g, narm, drop)
}

fvarsdCpp <- function(x, ng = 0L, g = 0L, gs = NULL, w = NULL, narm = TRUE, stable_algo = TRUE, sd = TRUE) {
    .Call(Cpp_fvarsd, x, ng, g, gs, w, narm, stable_algo, sd)
}

fvarsdmCpp <- function(x, ng = 0L, g = 0L, gs = NULL, w = NULL, narm = TRUE, stable_algo = TRUE, sd = TRUE, drop = TRUE) {
    .Call(Cpp_fvarsdm, x, ng, g, gs, w, narm, stable_algo, sd, drop)
}

fvarsdlCpp <- function(x, ng = 0L, g = 0L, gs = NULL, w = NULL, narm = TRUE, stable_algo = TRUE, sd = TRUE, drop = TRUE) {
    .Call(Cpp_fvarsdl, x, ng, g, gs, w, narm, stable_algo, sd, drop)
}

mrtl <- function(X, names = FALSE, ret = 0L) {
    .Call(Cpp_mrtl, X, names, ret)
}

mctl <- function(X, names = FALSE, ret = 0L) {
    .Call(Cpp_mctl, X, names, ret)
}

na_rm <- function(x) {
    .Call(Cpp_na_rm, x)
}

psmatCpp <- function(x, g, t = NULL, transpose = FALSE) {
    .Call(Cpp_psmat, x, g, t, transpose)
}

qFCpp <- function(x, ordered = FALSE) {
    .Call(Cpp_qF, x, ordered)
}

qGCpp <- function(x, ordered = FALSE) {
    .Call(Cpp_qG, x, ordered)
}

setAttributes <- function(x, a) {
    .Call(Cpp_setAttributes, x, a)
}

setattributes <- function(x, a) {
    invisible(.Call(Cpp_setattributes, x, a))
}

setAttr <- function(x, a, v) {
    .Call(Cpp_setAttr, x, a, v)
}

setattr_clp <- function(x, a, v) {
    invisible(.Call(Cpp_setattr_clp, x, a, v))
}

duplAttributes <- function(x, y) {
    .Call(Cpp_duplAttributes, x, y)
}

duplattributes <- function(x, y) {
    invisible(.Call(Cpp_duplattributes, x, y))
}

cond_duplAttributes <- function(x, y) {
    .Call(Cpp_cond_duplAttributes, x, y)
}

cond_duplattributes <- function(x, y) {
    invisible(.Call(Cpp_cond_duplattributes, x, y))
}

