# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BWCpp <- function(x, ng = 0L, g = 0L, gs = NULL, w = NULL, narm = TRUE, option = FALSE, B = FALSE) {
    .Call(`_collapse2_BWCpp`, x, ng, g, gs, w, narm, option, B)
}

BWmCpp <- function(x, ng = 0L, g = 0L, gs = NULL, w = NULL, narm = TRUE, option = FALSE, B = FALSE) {
    .Call(`_collapse2_BWmCpp`, x, ng, g, gs, w, narm, option, B)
}

BWlCpp <- function(x, ng = 0L, g = 0L, gs = NULL, w = NULL, narm = TRUE, option = FALSE, B = FALSE) {
    .Call(`_collapse2_BWlCpp`, x, ng, g, gs, w, narm, option, B)
}

TRACpp <- function(x, xAG, g = 0L, ret = 1L) {
    .Call(`_collapse2_TRACpp`, x, xAG, g, ret)
}

TRAmCpp <- function(x, xAG, g = 0L, ret = 1L) {
    .Call(`_collapse2_TRAmCpp`, x, xAG, g, ret)
}

TRAlCpp <- function(x, xAG, g = 0L, ret = 1L) {
    .Call(`_collapse2_TRAlCpp`, x, xAG, g, ret)
}

fNdistinctCpp <- function(x, ng = 0L, g = 0L, gs = NULL, narm = TRUE) {
    .Call(`_collapse2_fNdistinctCpp`, x, ng, g, gs, narm)
}

fNdistinctlCpp <- function(x, ng = 0L, g = 0L, gs = NULL, narm = TRUE, drop = TRUE) {
    .Call(`_collapse2_fNdistinctlCpp`, x, ng, g, gs, narm, drop)
}

fNdistinctmCpp <- function(x, ng = 0L, g = 0L, gs = NULL, narm = TRUE, drop = TRUE) {
    .Call(`_collapse2_fNdistinctmCpp`, x, ng, g, gs, narm, drop)
}

fbstatsCpp <- function(x, ext = FALSE, ng = 0L, g = 0L, npg = 0L, pg = 0L, w = NULL, array = TRUE, setn = TRUE, gn = NULL) {
    .Call(`_collapse2_fbstatsCpp`, x, ext, ng, g, npg, pg, w, array, setn, gn)
}

fbstatsmCpp <- function(x, ext = FALSE, ng = 0L, g = 0L, npg = 0L, pg = 0L, w = NULL, array = TRUE, gn = NULL) {
    .Call(`_collapse2_fbstatsmCpp`, x, ext, ng, g, npg, pg, w, array, gn)
}

fbstatslCpp <- function(x, ext = FALSE, ng = 0L, g = 0L, npg = 0L, pg = 0L, w = NULL, array = TRUE, gn = NULL) {
    .Call(`_collapse2_fbstatslCpp`, x, ext, ng, g, npg, pg, w, array, gn)
}

fdiffCpp <- function(x, n = 1L, diff = 1L, fill = NA_real_, ng = 0L, g = 0L, gs = NULL, t = NULL, names = TRUE) {
    .Call(`_collapse2_fdiffCpp`, x, n, diff, fill, ng, g, gs, t, names)
}

fdiffmCpp <- function(x, n = 1L, diff = 1L, fill = NA_real_, ng = 0L, g = 0L, gs = NULL, t = NULL, names = TRUE) {
    .Call(`_collapse2_fdiffmCpp`, x, n, diff, fill, ng, g, gs, t, names)
}

fdifflCpp <- function(x, n = 1L, diff = 1L, fill = NA_real_, ng = 0L, g = 0L, gs = NULL, t = NULL, names = TRUE) {
    .Call(`_collapse2_fdifflCpp`, x, n, diff, fill, ng, g, gs, t, names)
}

ffirstCpp <- function(x, ng = 0L, g = 0L, narm = TRUE) {
    .Call(`_collapse2_ffirstCpp`, x, ng, g, narm)
}

ffirstmCpp <- function(x, ng = 0L, g = 0L, narm = TRUE, drop = TRUE) {
    .Call(`_collapse2_ffirstmCpp`, x, ng, g, narm, drop)
}

ffirstlCpp <- function(x, ng = 0L, g = 0L, narm = TRUE) {
    .Call(`_collapse2_ffirstlCpp`, x, ng, g, narm)
}

fgrowthCpp <- function(x, n = 1L, diff = 1L, fill = NA_real_, ng = 0L, g = 0L, gs = NULL, t = NULL, logdiff = FALSE, names = TRUE) {
    .Call(`_collapse2_fgrowthCpp`, x, n, diff, fill, ng, g, gs, t, logdiff, names)
}

fgrowthmCpp <- function(x, n = 1L, diff = 1L, fill = NA_real_, ng = 0L, g = 0L, gs = NULL, t = NULL, logdiff = FALSE, names = TRUE) {
    .Call(`_collapse2_fgrowthmCpp`, x, n, diff, fill, ng, g, gs, t, logdiff, names)
}

fgrowthlCpp <- function(x, n = 1L, diff = 1L, fill = NA_real_, ng = 0L, g = 0L, gs = NULL, t = NULL, logdiff = FALSE, names = TRUE) {
    .Call(`_collapse2_fgrowthlCpp`, x, n, diff, fill, ng, g, gs, t, logdiff, names)
}

flagleadCpp <- function(x, n = 1L, fill = NULL, ng = 0L, g = 0L, gs = NULL, t = NULL, names = TRUE) {
    .Call(`_collapse2_flagleadCpp`, x, n, fill, ng, g, gs, t, names)
}

flagleadmCpp <- function(x, n = 1L, fill = NULL, ng = 0L, g = 0L, gs = NULL, t = NULL, names = TRUE) {
    .Call(`_collapse2_flagleadmCpp`, x, n, fill, ng, g, gs, t, names)
}

flagleadlCpp <- function(x, n = 1L, fill = NULL, ng = 0L, g = 0L, gs = NULL, t = NULL, names = TRUE) {
    .Call(`_collapse2_flagleadlCpp`, x, n, fill, ng, g, gs, t, names)
}

flastCpp <- function(x, ng = 0L, g = 0L, narm = TRUE) {
    .Call(`_collapse2_flastCpp`, x, ng, g, narm)
}

flastmCpp <- function(x, ng = 0L, g = 0L, narm = TRUE, drop = TRUE) {
    .Call(`_collapse2_flastmCpp`, x, ng, g, narm, drop)
}

flastlCpp <- function(x, ng = 0L, g = 0L, narm = TRUE) {
    .Call(`_collapse2_flastlCpp`, x, ng, g, narm)
}

fmaxCpp <- function(x, ng = 0L, g = 0L, narm = TRUE) {
    .Call(`_collapse2_fmaxCpp`, x, ng, g, narm)
}

fmaxmCpp <- function(x, ng = 0L, g = 0L, narm = TRUE, drop = TRUE) {
    .Call(`_collapse2_fmaxmCpp`, x, ng, g, narm, drop)
}

fmaxlCpp <- function(x, ng = 0L, g = 0L, narm = TRUE, drop = TRUE) {
    .Call(`_collapse2_fmaxlCpp`, x, ng, g, narm, drop)
}

fmeanCpp <- function(x, ng = 0L, g = 0L, gs = NULL, w = NULL, narm = TRUE) {
    .Call(`_collapse2_fmeanCpp`, x, ng, g, gs, w, narm)
}

fmeanmCpp <- function(x, ng = 0L, g = 0L, gs = NULL, w = NULL, narm = TRUE, drop = TRUE) {
    .Call(`_collapse2_fmeanmCpp`, x, ng, g, gs, w, narm, drop)
}

fmeanlCpp <- function(x, ng = 0L, g = 0L, gs = NULL, w = NULL, narm = TRUE, drop = TRUE) {
    .Call(`_collapse2_fmeanlCpp`, x, ng, g, gs, w, narm, drop)
}

fmedianCpp <- function(x, ng = 0L, g = 0L, gs = NULL, narm = TRUE) {
    .Call(`_collapse2_fmedianCpp`, x, ng, g, gs, narm)
}

fmedianmCpp <- function(x, ng = 0L, g = 0L, gs = NULL, narm = TRUE, drop = TRUE) {
    .Call(`_collapse2_fmedianmCpp`, x, ng, g, gs, narm, drop)
}

fmedianlCpp <- function(x, ng = 0L, g = 0L, gs = NULL, narm = TRUE, drop = TRUE) {
    .Call(`_collapse2_fmedianlCpp`, x, ng, g, gs, narm, drop)
}

fminCpp <- function(x, ng = 0L, g = 0L, narm = TRUE) {
    .Call(`_collapse2_fminCpp`, x, ng, g, narm)
}

fminmCpp <- function(x, ng = 0L, g = 0L, narm = TRUE, drop = TRUE) {
    .Call(`_collapse2_fminmCpp`, x, ng, g, narm, drop)
}

fminlCpp <- function(x, ng = 0L, g = 0L, narm = TRUE, drop = TRUE) {
    .Call(`_collapse2_fminlCpp`, x, ng, g, narm, drop)
}

fmodeCpp <- function(x, ng = 0L, g = 0L, gs = NULL, w = NULL, narm = TRUE) {
    .Call(`_collapse2_fmodeCpp`, x, ng, g, gs, w, narm)
}

fmodelCpp <- function(x, ng = 0L, g = 0L, gs = NULL, w = NULL, narm = TRUE) {
    .Call(`_collapse2_fmodelCpp`, x, ng, g, gs, w, narm)
}

fmodemCpp <- function(x, ng = 0L, g = 0L, gs = NULL, w = NULL, narm = TRUE, drop = TRUE) {
    .Call(`_collapse2_fmodemCpp`, x, ng, g, gs, w, narm, drop)
}

fnobsCpp <- function(x, ng = 0L, g = 0L) {
    .Call(`_collapse2_fnobsCpp`, x, ng, g)
}

fnobsmCpp <- function(x, ng = 0L, g = 0L, drop = TRUE) {
    .Call(`_collapse2_fnobsmCpp`, x, ng, g, drop)
}

fnobslCpp <- function(x, ng = 0L, g = 0L, drop = TRUE) {
    .Call(`_collapse2_fnobslCpp`, x, ng, g, drop)
}

fprodCpp <- function(x, ng = 0L, g = 0L, narm = TRUE) {
    .Call(`_collapse2_fprodCpp`, x, ng, g, narm)
}

fprodmCpp <- function(x, ng = 0L, g = 0L, narm = TRUE, drop = TRUE) {
    .Call(`_collapse2_fprodmCpp`, x, ng, g, narm, drop)
}

fprodlCpp <- function(x, ng = 0L, g = 0L, narm = TRUE, drop = TRUE) {
    .Call(`_collapse2_fprodlCpp`, x, ng, g, narm, drop)
}

fscaleCpp <- function(x, ng = 0L, g = 0L, gs = NULL, w = NULL, narm = TRUE, stable_algo = TRUE) {
    .Call(`_collapse2_fscaleCpp`, x, ng, g, gs, w, narm, stable_algo)
}

fscalemCpp <- function(x, ng = 0L, g = 0L, gs = NULL, w = NULL, narm = TRUE, stable_algo = TRUE) {
    .Call(`_collapse2_fscalemCpp`, x, ng, g, gs, w, narm, stable_algo)
}

fscalelCpp <- function(x, ng = 0L, g = 0L, gs = NULL, w = NULL, narm = TRUE, stable_algo = TRUE) {
    .Call(`_collapse2_fscalelCpp`, x, ng, g, gs, w, narm, stable_algo)
}

fsumCpp <- function(x, ng = 0L, g = 0L, narm = TRUE) {
    .Call(`_collapse2_fsumCpp`, x, ng, g, narm)
}

fsummCpp <- function(x, ng = 0L, g = 0L, narm = TRUE, drop = TRUE) {
    .Call(`_collapse2_fsummCpp`, x, ng, g, narm, drop)
}

fsumlCpp <- function(x, ng = 0L, g = 0L, narm = TRUE, drop = TRUE) {
    .Call(`_collapse2_fsumlCpp`, x, ng, g, narm, drop)
}

fvarsdCpp <- function(x, ng = 0L, g = 0L, gs = NULL, w = NULL, narm = TRUE, stable_algo = TRUE, sd = TRUE) {
    .Call(`_collapse2_fvarsdCpp`, x, ng, g, gs, w, narm, stable_algo, sd)
}

fvarsdmCpp <- function(x, ng = 0L, g = 0L, gs = NULL, w = NULL, narm = TRUE, stable_algo = TRUE, sd = TRUE, drop = TRUE) {
    .Call(`_collapse2_fvarsdmCpp`, x, ng, g, gs, w, narm, stable_algo, sd, drop)
}

fvarsdlCpp <- function(x, ng = 0L, g = 0L, gs = NULL, w = NULL, narm = TRUE, stable_algo = TRUE, sd = TRUE, drop = TRUE) {
    .Call(`_collapse2_fvarsdlCpp`, x, ng, g, gs, w, narm, stable_algo, sd, drop)
}

mrtl <- function(X, names = FALSE, ret = 0L) {
    .Call(`_collapse2_mrtl`, X, names, ret)
}

mctl <- function(X, names = FALSE, ret = 0L) {
    .Call(`_collapse2_mctl`, X, names, ret)
}

qFCpp <- function(x, ordered = FALSE) {
    .Call(`_collapse2_qFCpp`, x, ordered)
}

qGCpp <- function(x, ordered = FALSE) {
    .Call(`_collapse2_qGCpp`, x, ordered)
}

